name: Docker build, scan and push 

on:
  push:
    branches:
        - main

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build:
        runs-on: ubuntu-latest

        outputs:
         image_name_lowercase: ${{ steps.repo-name.outputs.image_name_lowercase }}
        

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Repo name to lower case
              id: repo-name
              run: echo "image_name_lowercase=$(echo '${{ env.IMAGE_NAME }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4

            - name: Build and export Image artifact
              uses: docker/build-push-action@v7
              with:
                context: .
                push: false
                pull: true
                cache-from: type=gha
                cachec-to: type=gha,mode=max
                tags: ${{ env.REGISTRY }}/${{ steps.repo-name.outputs.image_name_lowercase }}:${{ github.sha }}
                build-args: |
                  VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}
                  VITE_SUPABASE_PUBLISHABLE_KEY=${{ secrets.VITE_SUPABASE_PUBLISHABLE_KEY }}
                outputs: type=docker,dest=${{ runner.temp }}/image.tar

            - name: Upload Image artifact
              uses: actions/upload-artifact@v7
              with:
                name: react-app-image
                path: ${{ runner.temp }}/image.tar
                retention-days: 1


    Scan-and-push:
        runs-on: ubuntu-latest
        needs: build

        permissions:
            contents: read
            packages: write

        steps:

            - name: download Image artifact
              uses: actions/download-artifact@v7
              with:
                name: react-app-image
                path: ${{ runner.temp }}

            - name: load Image artifact
              run: docker load -i ${{ runner.temp }}/image.tar

            - name: Scan Image with Trivy
              uses: aquasecurity/trivy-action@v0.36.0
              with:
                image-ref: ${{ env.REGISTRY }}/${{ needs.build.outputs.image_name_lowercase }}:${{ github.sha }}
                format: 'table'
                output: 'scan-results.txt'
                exit-code: '1'
                severity: 'CRITICAL,HIGH'

            - name: Upload TrivyScan Results
              if: always()
              uses: actions/upload-artifact@v7
              with:
                name: scan-results
                path: scan-results.txt

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Push Image to GitHub Container Registry
              run: docker push ${{ env.REGISTRY }}/${{ needs.build.outputs.image_name_lowercase }}:${{ github.sha }}

            





          